// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: lib/fakebash/pb/fakebash.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandResponse_Type int32

const (
	CommandResponse_STDOUT CommandResponse_Type = 0
	CommandResponse_STDERR CommandResponse_Type = 1
	CommandResponse_EXIT   CommandResponse_Type = 2
)

// Enum value maps for CommandResponse_Type.
var (
	CommandResponse_Type_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
		2: "EXIT",
	}
	CommandResponse_Type_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
		"EXIT":   2,
	}
)

func (x CommandResponse_Type) Enum() *CommandResponse_Type {
	p := new(CommandResponse_Type)
	*p = x
	return p
}

func (x CommandResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_fakebash_pb_fakebash_proto_enumTypes[0].Descriptor()
}

func (CommandResponse_Type) Type() protoreflect.EnumType {
	return &file_lib_fakebash_pb_fakebash_proto_enumTypes[0]
}

func (x CommandResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandResponse_Type.Descriptor instead.
func (CommandResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_lib_fakebash_pb_fakebash_proto_rawDescGZIP(), []int{1, 0}
}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Cwd           string                 `protobuf:"bytes,2,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env           []string               `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_lib_fakebash_pb_fakebash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_fakebash_pb_fakebash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_lib_fakebash_pb_fakebash_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *CommandRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandResponse_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=fakebash.CommandResponse_Type" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_lib_fakebash_pb_fakebash_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_fakebash_pb_fakebash_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_lib_fakebash_pb_fakebash_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetType() CommandResponse_Type {
	if x != nil {
		return x.Type
	}
	return CommandResponse_STDOUT
}

func (x *CommandResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_lib_fakebash_pb_fakebash_proto protoreflect.FileDescriptor

const file_lib_fakebash_pb_fakebash_proto_rawDesc = "" +
	"\n" +
	"\x1elib/fakebash/pb/fakebash.proto\x12\bfakebash\"H\n" +
	"\x0eCommandRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x02 \x01(\tR\x03cwd\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\"\x89\x01\n" +
	"\x0fCommandResponse\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.fakebash.CommandResponse.TypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"(\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\x12\b\n" +
	"\x04EXIT\x10\x022V\n" +
	"\x0fFakebashService\x12C\n" +
	"\n" +
	"RunCommand\x12\x18.fakebash.CommandRequest\x1a\x19.fakebash.CommandResponse0\x01B/Z-github.com/AgentDrasil/asgard/lib/fakebash/pbb\x06proto3"

var (
	file_lib_fakebash_pb_fakebash_proto_rawDescOnce sync.Once
	file_lib_fakebash_pb_fakebash_proto_rawDescData []byte
)

func file_lib_fakebash_pb_fakebash_proto_rawDescGZIP() []byte {
	file_lib_fakebash_pb_fakebash_proto_rawDescOnce.Do(func() {
		file_lib_fakebash_pb_fakebash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_fakebash_pb_fakebash_proto_rawDesc), len(file_lib_fakebash_pb_fakebash_proto_rawDesc)))
	})
	return file_lib_fakebash_pb_fakebash_proto_rawDescData
}

var file_lib_fakebash_pb_fakebash_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lib_fakebash_pb_fakebash_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_fakebash_pb_fakebash_proto_goTypes = []any{
	(CommandResponse_Type)(0), // 0: fakebash.CommandResponse.Type
	(*CommandRequest)(nil),    // 1: fakebash.CommandRequest
	(*CommandResponse)(nil),   // 2: fakebash.CommandResponse
}
var file_lib_fakebash_pb_fakebash_proto_depIdxs = []int32{
	0, // 0: fakebash.CommandResponse.type:type_name -> fakebash.CommandResponse.Type
	1, // 1: fakebash.FakebashService.RunCommand:input_type -> fakebash.CommandRequest
	2, // 2: fakebash.FakebashService.RunCommand:output_type -> fakebash.CommandResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lib_fakebash_pb_fakebash_proto_init() }
func file_lib_fakebash_pb_fakebash_proto_init() {
	if File_lib_fakebash_pb_fakebash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_fakebash_pb_fakebash_proto_rawDesc), len(file_lib_fakebash_pb_fakebash_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_fakebash_pb_fakebash_proto_goTypes,
		DependencyIndexes: file_lib_fakebash_pb_fakebash_proto_depIdxs,
		EnumInfos:         file_lib_fakebash_pb_fakebash_proto_enumTypes,
		MessageInfos:      file_lib_fakebash_pb_fakebash_proto_msgTypes,
	}.Build()
	File_lib_fakebash_pb_fakebash_proto = out.File
	file_lib_fakebash_pb_fakebash_proto_goTypes = nil
	file_lib_fakebash_pb_fakebash_proto_depIdxs = nil
}
