// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: lib/fakebash/pb/fakebash.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FakebashService_RunCommand_FullMethodName = "/fakebash.FakebashService/RunCommand"
)

// FakebashServiceClient is the client API for FakebashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FakebashServiceClient interface {
	RunCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandResponse], error)
}

type fakebashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFakebashServiceClient(cc grpc.ClientConnInterface) FakebashServiceClient {
	return &fakebashServiceClient{cc}
}

func (c *fakebashServiceClient) RunCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FakebashService_ServiceDesc.Streams[0], FakebashService_RunCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CommandRequest, CommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FakebashService_RunCommandClient = grpc.ServerStreamingClient[CommandResponse]

// FakebashServiceServer is the server API for FakebashService service.
// All implementations must embed UnimplementedFakebashServiceServer
// for forward compatibility.
type FakebashServiceServer interface {
	RunCommand(*CommandRequest, grpc.ServerStreamingServer[CommandResponse]) error
	mustEmbedUnimplementedFakebashServiceServer()
}

// UnimplementedFakebashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFakebashServiceServer struct{}

func (UnimplementedFakebashServiceServer) RunCommand(*CommandRequest, grpc.ServerStreamingServer[CommandResponse]) error {
	return status.Error(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedFakebashServiceServer) mustEmbedUnimplementedFakebashServiceServer() {}
func (UnimplementedFakebashServiceServer) testEmbeddedByValue()                         {}

// UnsafeFakebashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FakebashServiceServer will
// result in compilation errors.
type UnsafeFakebashServiceServer interface {
	mustEmbedUnimplementedFakebashServiceServer()
}

func RegisterFakebashServiceServer(s grpc.ServiceRegistrar, srv FakebashServiceServer) {
	// If the following call panics, it indicates UnimplementedFakebashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FakebashService_ServiceDesc, srv)
}

func _FakebashService_RunCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FakebashServiceServer).RunCommand(m, &grpc.GenericServerStream[CommandRequest, CommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FakebashService_RunCommandServer = grpc.ServerStreamingServer[CommandResponse]

// FakebashService_ServiceDesc is the grpc.ServiceDesc for FakebashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FakebashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fakebash.FakebashService",
	HandlerType: (*FakebashServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunCommand",
			Handler:       _FakebashService_RunCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lib/fakebash/pb/fakebash.proto",
}
