name: Test on Push

on:
  push:
    branches: [ main ]

env:
  GO_VERSION: 1.26
  GOIMPORTS_VERSION: latest
  GOLANGCI_LINT_VERSION: latest
  NODE_VERSION: 26

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@${{ env.GOIMPORTS_VERSION }}

    - name: Format check
      run: |
        $(go env GOPATH)/bin/goimports -l .

    - name: Lint check
      uses: golangci/golangci-lint-action@v9
      with:
        version: ${{ env.GOLANGCI_LINT_VERSION }}

    - name: Run tests
      run: |
        go test -v ./...

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webui
    steps:
    - uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: webui/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Lint check
      run: npm run lint

    - name: Format check
      run: npm run fmt:check

    - name: Run tests
      run: npm run test

    - name: Build
      run: npm run build
